# Generated by Django 4.2.5 on 2023-09-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_post_author_alter_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='responses',
            name='test',
            field=models.TextField(),
        ),
    ]
