# Generated by Django 4.2.5 on 2023-09-22 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0005_alter_post_category_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='test',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='responses',
            name='re_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
