# Generated by Django 4.2.5 on 2023-09-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='file',
        ),
    ]
