# Generated by Django 4.2.5 on 2023-10-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_rename_picture_post_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletters',
        ),
    ]
